server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      default-filters:
        - JwtAuthenticationFilter
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**
        - id: warehouse-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/warehouses/**
        - id: inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/inventory/**
        - id: order-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/orders/**
        - id: shipping-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/shipping/**

jwt:
  secret: c3VwZXItc2VjcmV0LWtleS1zaG91bGQtYmUtYXQtbGVhc3QtMjU2LWJpdHMtbG9uZy1mb3Itc2hhMjU2
